### ISSUE TITLE
Mother-in-law not shown

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#95]
I am not sure when this issue came up first, but it seems to exist (for me) at least since version 48. The respective section says:

**Parents-in-law**
(Proband) has one father-in-law recorded.
**Marriage with (wife)**
Marriage (father-in-law) + (mother-in-law)

And in the box it then only shows the father-in-law although there clearly is a mother-in-law as well. As far as I can tell there is nothing special about this marriage, no privacy restrictions, no nothing.

**Comment by hartenthaler** [comment]
yes, I can see it, too.

**Comment by hartenthaler** [comment]
fixed! Will be part of next release.

**Comment by TheDutchJewel** [comment]
I still don't see the mother-in-law in the Parents-in-law section.

**Comment by hartenthaler** [comment]
... there was a bug and I fixed it. Maybe there is still another bug. Do you miss the mother-in-law in all families or only in some of them?

**Comment by hartenthaler** [comment]
... or there is a problem that the new file "ExtendedFamily.php" is not loaded and you are still using a cashed old version. I'm not sure that I'm really understanding the now-used autoload feature. Can you upload all module files again, please? And close/open your browser again? Does this help? I just checked: the files in the zip-File 2.0.16.50 are the newest one and should be ok.

**Comment by TheDutchJewel** [comment]
I had to remove the old version to get the new one working. See [issue #102](https://github.com/hartenthaler/hh_extended_family/issues/102).

**Comment by reteP-riS** [comment]
The original issue with the mother-in-law missing was successfully fixed. Thank you!
